### PR TITLE
Fix for AWS Lambda Container Handler

### PR DESCRIPTION
**Pull request by ShashankMishra**
Fix for AWS Lambda Container handler which match consume media type, Changed consume to supported mediatype array

### CODE REVIEW

**Comment by marceloverdijk** [comment]
@ShashankMishra from the change I can see that `MediaType.ALL` was removed.
This is there explicitly to accept `POST` requests without a content type defined. 

With your (proposed) change only `{MediaType.APPLICATION_JSON, MediaType.APPLICATION_GRAPHQL}` will be supported.

A `POST` without content type should be supported per this recommendation in the GraphQL spec regarding `POST` requests:
> If the "query" query string parameter is present (as in the GET example above),
> it should be parsed and handled in the same way as the HTTP GET case.

**Comment by ShashankMishra** [comment]
> @ShashankMishra from the change I can see that `MediaType.ALL` was removed.
> This is there explicitly to accept `POST` requests without a content type defined.
> 
> With your (proposed) change only `{MediaType.APPLICATION_JSON, MediaType.APPLICATION_GRAPHQL}` will be supported.
> 
> A `POST` without content type should be supported per this recommendation in the GraphQL spec regarding `POST` requests:
> 
> > If the "query" query string parameter is present (as in the GET example above),
> > it should be parsed and handled in the same way as the HTTP GET case.

It is causing an issue with MicronanutLambdaContainerHandler for AWS Lambda...
Please find below code :

```
final MediaType requestContentType = containerRequest.getContentType().orElse(null);

                        if (expectedContentType.length > 0 && Arrays.stream(expectedContentType).noneMatch(ct -> ct.equals(requestContentType))) {
                            containerResponse.status(HttpStatus.UNSUPPORTED_MEDIA_TYPE);
                            containerResponse.close();
                            return;
                        }

```

As you can see, it checks for supported media type to matched with at least one.
can we have separately defined ALL with JSON and GraphQL media types as well.

Something like below :
`consumes = {MediaType.APPLICATION_JSON,MediaType.APPLICATION_GRAPHQL,MediaType.ALL}`

**Comment by marceloverdijk** [comment]
I'm not familiar enough with the `MicronanutLambdaContainerHandler` but I think it should check the presence of `MediaType.ALL` as well and not only doing a actual comparison. 

WDYT @graemerocher ?

**Comment by ShashankMishra** [comment]
@marceloverdijk agree, I'll raise PR there for it. Thanks for all your help.

**Comment by ShashankMishra** [comment]
@graemerocher PR raised - https://github.com/micronaut-projects/micronaut-aws/pull/158

@marceloverdijk Closing this, thanks.

**Pull request closed without merging**
