### PR TITLE
issue_33

### LINKED ISSUE #33: GraphQLWsController is heavy on logs
This ticket is related to https://github.com/micronaut-projects/micronaut-graphql/blob/774dc9b14f5359d334b5e55dbc5480cfcfbb5696/graphql/src/main/java/io/micronaut/configuration/graphql/ws/GraphQLWsController.java#L88

On every page refresh onClose and onOpen is logged at info level. I could just filter info from logback.xml, but `onError` is logging at the same level. This makes distinguishing between 'normal' and 'exceptional' flow difficult. Generally speaking, my problem is solved as long as the `onOpen()', 'onClose()` are different from `onError`. 

Having said that, I believe log levels for `onOpen()` and `onClose()` should be trace or at most debug level. `onError` should be considered debug or at most info.

### PR DESCRIPTION
**Pull request by weisheme**
Fixes #33

### CODE REVIEW

**Comment by marceloverdijk** [comment]
@gklijs what do you think?

**Comment by gklijs** [comment]
I don't have a strong preference. I'm kind of used having production set to warn, so in that case it's no issue anyway, but don't mind setting them to trace here.

**Comment by marceloverdijk** [comment]
I think for `onOpen` and `onClose` `trace` is indeed good.
I'm only unsure about `onError`... is `debug` or even `info` sufficient here?

**Comment by gklijs** [comment]
I guess debug is fine for `onError`, it will trigger often, often when disconnecting, so in the front-end when navigating to another page, or closing the browser.

**Comment by marceloverdijk** [comment]
Thanks @gklijs I will then merge this PR.
PS: Did you tested `1.3.0.RC1` and feel comfortable with a GA release?

**Comment by gklijs** [comment]
Yes, comfortable enough at least. There is currently a weird bottle neck, https://graphql.gklijs.tech/results/graphql-servers-feb/transactions-per-second, but that could be solved later on. I'm also not sure if it's related to this library, or just how websockets are implemented for Micronaut.

**Pull request merged**
