### PR TITLE
fix broken build and bring up to date with respect to build plugins 6.1.1

### LINKED ISSUE #318: Grapqhl Master branch pointing to 4.0.0-SNAPSHOT is broken
### Issue description

We will have to update it to the latest

### PR DESCRIPTION
**Pull request by wetted**
fixes #318

### CODE REVIEW

**Comment by timyates** [comment]
Fixed the tests, but now there's a Graal issue...  I can't see why logback is getting onto the compile classpath

**Comment by timyates** [comment]
GraalVM tests fixed by https://github.com/micronaut-projects/micronaut-security/pull/1171

**Review by timyates — COMMENTED** [review]
Not sure why we were forcing dependencies, so I removed that

https://github.com/micronaut-projects/micronaut-graphql/pull/327/commits/37e55ae48441c2a66ee587a019cfab103986e94a

@wetted PTAL

**Review by timyates — APPROVED** [review]

**Comment by timyates** [comment]
@sdelamo this can be merged afaict.  I can't do it, as we seem to require a Java 11 and 8 build, and I can't turn that off

**Review by sdelamo — APPROVED** [review]

**Pull request merged**
