### PR TITLE
build: Micronaut 3.5.4

### PR DESCRIPTION
**Pull request by sdelamo**
- Micronaut to 3.5.4
- Micronaut Test to 3.4.0
- Groovy to 3.0.12
- Spock to 2.1
- `githubCoreBranch` to 3.6.x

### CODE REVIEW

**Comment by sdelamo** [comment]
@timyates can you investigate the failure?

**Comment by sdelamo** [comment]
@timyates can you investigate the failure?

**Comment by timyates** [comment]
👀

**Comment by timyates** [comment]
Failing on 22.3-dev

Works locally on 22.2

Downloading 22.3-dev JVM to test that

**Comment by timyates** [comment]
The failure here is for the 22.3-dev version, but it fails on 22.2 as well

**Comment by timyates** [comment]
@sdelamo My crystal ball 🔮 says this will go green now (thanks to @melix for all the help) 😎

**Review by melix — APPROVED** [review]

**Pull request merged**
