### PR TITLE
Add test-suite for jackson and serde with empty result

### PR DESCRIPTION
**Pull request by timyates**
Jackson fails as serialized empty model is empty?

### CODE REVIEW

**Comment by timyates** [comment]
@guillermocalvo Any ideas?  As you can see, the jackson suite test fails https://ge.micronaut.io/s/ztlpq3ykstzv2/tests/overview?outcome=FAILED

**Comment by guillermocalvo** [comment]
> Any ideas? As you can see, the jackson suite test fails https://ge.micronaut.io/s/ztlpq3ykstzv2/tests/overview?outcome=FAILED

@timyates I found two ways to make the jackson test pass:

1. Adding property `jackson.serialization-inclusion=ALWAYS` to the test.
2. OR removing the `@Serdeable` annotation from class `GraphQLResponseBody`.

So I believe there must be some kind of bug in Micronaut Serde that makes the serialization process ignore the `@JsonInclude` annotation on class fields when it's annotated as `@Serdeable`. Does that make sense? 🤔 

@yawkat Do you think this problem should be fixed by https://github.com/micronaut-projects/micronaut-core/pull/9872 ?

**Review by sdelamo — CHANGES_REQUESTED** [review]
don't use yaml for configuration use `application.properties`

annotate beans with `@Requires(property = "spec.name" and `@Property(name = "spec.name" to avoid bean pollution in the `test-suite-serde` and `test-suite-jackson` modules.

**Comment by sdelamo** [comment]
@timyates Making the Jackson tests not use a `@Serdeable` but `@Introspected` class seems to have fixed the issue.

**Comment by yawkat** [comment]
if it breaks with Serdeable but not Introspected, I strongly suspect micronaut-serialization is involved in some way.

**Comment by timyates** [comment]
That doesn't help us with the GraphQL todo guide, as it looks like the `ToDo` class is annotated with `@MappedEntity`

This PR was to show the error we were seeing in the guide, and I'm not sure how the fixes fix it...

- I can't see how we could use `jackson.serialization-inclusion=ALWAYS`, as it may fix the test but won't it still fail when the user makes the query in the running app?
- None of the classes in the Guide are `@Introspected`

The only fix I could get to work in the guide was to switch to use serde instead of miconaut-jackson-databind

**Comment by timyates** [comment]
@sdelamo converted back to a draft, as I don't believe this should be merged as-is

**Comment by guillermocalvo** [comment]
> I can't see how we could use `jackson.serialization-inclusion=ALWAYS`, as it may fix the test but won't it still fail when the user makes the query in the running app?

@timyates My bad, I didn't mean using `jackson.serialization-inclusion=ALWAYS` should be the solution to this problem. And I don't think removing the `@Serdeable` annotation is the way to go, either.

I did those experiments just to help diagnose what was going on. As I believe @yawkat is suggesting, this issue should be addressed in [micronaut-serialization](https://github.com/micronaut-projects/micronaut-serialization). Only when it's fixed there we can use the latest version here and everything should work fine as it is now.

**Comment by timyates** [comment]
The GraphQL guide I mention works now, and I can't 100% remember what the issue here was...I'm going to close this, and we can re-visit if we see it again...

**Pull request closed without merging**
