### PR TITLE
GraphQL annotations to define DataFetchers and TypeResolvers

### PR DESCRIPTION
**Pull request by dstepanov**
I have written on Gitter about GraphQL annotations I have created to easily map DataFetcher and TypeResolver.

Not sure which branch should I use for this PR.

### CODE REVIEW

**Comment by dstepanov** [comment]
@jameskleeh I have created PR based on our discussion yesterday, let me know if there anything more I can add.

**Comment by benmccann** [comment]
It sounds like there was some conversation on Gitter that I missed. It might be helpful to put some overview in the PR description

I'm wondering if we can use what's provided by graphql-java rather than introducing new duplicate concepts? E.g. instead of introducing `GraphQLDataFetcher` can we use the existing `graphql.schema.DataFetcher`?

**Comment by dstepanov** [comment]
@benmccann GraphQLDataFetcher is just an annotation, I'm not aware of existing annotations.

The PR just adds an ability to create the runtime using added annotations, no new concepts.

**Comment by benmccann** [comment]
Right, but why not use the existing interfaces instead of introducing new annotations?

**Comment by dstepanov** [comment]
If you want to use existing interfaces you can, annotations just simplify configuration for you.

**Comment by benmccann** [comment]
I feel like this might be better as an external library. E.g. there's [one example for using Micronaut with graphql-java-tools](https://github.com/micronaut-projects/micronaut-graphql/tree/master/examples/todo-java-tools), [one with using SPQR](https://github.com/micronaut-projects/micronaut-graphql/tree/master/examples/todo-spqr), and we could add another example of using Micronaut with these annotations. The problem with building it into this library is that there are lots of ways to setup your GraphQL project. For someone who's using graphql-java-tools or SPQR they will have duplicate setup methods included in their project. That has the potential to confuse other people on their teams. If you see graphql-java-tools and micronaut-graphql included in your project do you use the graphql-java-tools classes or these annotations? Today that confusion wouldn't exist and I'm weary of introducing it.

Making it external would also provide benefit to other users because users who are not using Micronaut could still benefit from your work.

**Comment by graemerocher** [comment]
Just revisiting this, maybe if was a separate module of this library?

**Comment by hc-codersatlas** [comment]
> I feel like this might be better as an external library. E.g. there's [one example for using Micronaut with graphql-java-tools](https://github.com/micronaut-projects/micronaut-graphql/tree/master/examples/todo-java-tools), [one with using SPQR](https://github.com/micronaut-projects/micronaut-graphql/tree/master/examples/todo-spqr), and we could add another example of using Micronaut with these annotations. The problem with building it into this library is that there are lots of ways to setup your GraphQL project. For someone who's using graphql-java-tools or SPQR they will have duplicate setup methods included in their project. That has the potential to confuse other people on their teams. If you see graphql-java-tools and micronaut-graphql included in your project do you use the graphql-java-tools classes or these annotations? Today that confusion wouldn't exist and I'd be weary of introducing it.
> 
> Making it external would also provide benefit to other users because users who are not using Micronaut could still benefit from your work.

Problem is SPQR hasn't been updated in a long time, isn't well documented and is e..g behind on the latest java-graphql releases  etc. graphql-java-tools requires kotlin and other things that may not be suitable. Quarkus has added some support recently. Would be good if Micronaut can also for Micronaut users.

**Comment by benmccann** [comment]
Those are good reasons to create a new library, but not necessarily good reasons to make it part of Micronaut. I still think the functionality would best live outside this project. Then you could share the functionality between Quarkus and Micronaut for example

**Comment by dstepanov** [comment]
I'm a bit lost with the discussion, I have only added a few annotations to simplify the configuration of `TypeRuntimeWiring`.
Not sure what do you mean by sharing a functionality, there is zero functionality, just an annotation-based configuration for `TypeRuntimeWiring`.

I don't use GraphQL at the moment so I don't really know what is the state of graphql java library, but that was a pretty easy thing to add and it replaced the manual configuration of every `DataFetcher` in the project.

**Comment by marceloverdijk** [comment]
Quarkus supports quite some Eclipse MicroProfile specs using the SmallRye implementations. This includes the MicroProfile GraphQL spec / SmallRye GraphQL implementation.

Note that SPQR is also compliant with the MP spec and even helped forming this spec.

Of course it would be nice if Micronaut could support a similar code first approach using annotations.
But would it be best to introduce a Micronaut specific set of annotations or e.g. use the MP GraphQL spec?

**Comment by graemerocher** [comment]
If the spec provides a dependency free set of annotations it is fine to use those IMO

**Comment by marceloverdijk** [comment]
Yes I fully agree @graemerocher (why re-inventing the wheel)

**Comment by dstepanov** [comment]
MP GraphQL spec looks good, it's better to have some implementation using those annotations.

**Pull request closed without merging**
