### PR TITLE
Migrate to Gradle Version Catalog and upgrade to use latest stable versions

### PR DESCRIPTION
**Pull request by donbeave**
This PR includes an update for several dependencies:

1) Micronaut 3.3.4
2) graphql-java 18.0
3) graphql-java-tools 12.0.2

Synced project to the https://github.com/micronaut-projects/micronaut-project-template repository.

Migrated to Gradle Version Catalogs.

### CODE REVIEW

**Comment by donbeave** [comment]
I have verified all examples are working correctly with these upgrades.

**Comment by sdelamo** [comment]
> I have verified all examples are working correctly with these upgrades.

We are going to [migrate the examples to guides](https://github.com/micronaut-projects/micronaut-graphql/issues/241). in case, If you are interested in contributing to that migration.

**Review by patrickdronk — DISMISSED** [review]

**Comment by donbeave** [comment]
Can this PR be merged?

**Comment by donbeave** [comment]
@alvarosanchez I have fixed the GraalVM build, but Sonaqube task still failing:

```
Execution failed for task ':sonarqube'.
[2489](https://github.com/micronaut-projects/micronaut-graphql/runs/6235080194?check_suite_focus=true#step:7:2489)
> Unable to load component class org.sonar.scanner.scan.filesystem.ProjectFileIndexer
```

I'm not very sure, but it can be the issue with the Sonarqube Groovy plugin: https://community.sonarsource.com/t/unable-to-load-component-class-org-sonar-scanner-scan-filesystem-projectfileindexer/41352

P.S. Also this PR added a migration to Gradle Version Catalog.

**Comment by alvarosanchez** [comment]
Don't worry about the Sonarqube workflow. It's failing because GitHub won't expose the Sonar secret to workflows triggered from forked repos. Known limitation.

**Comment by donbeave** [comment]
Can we merge this PR?

**Comment by donbeave** [comment]
@alvarosanchez @sdelamo I'm really sorry for pushing... Can this PR be merged?

**Comment by timyates** [comment]
Thanks again @donbeave 😎 👍 

Superseded by https://github.com/micronaut-projects/micronaut-graphql/pull/280

I rolled back the version updates, as this would require a major release of this, and Micronaut 4.0.0

**Pull request closed without merging**
