### PR TITLE
Add support for graphql over web sockets, supporting queries, mutatio…

### PR DESCRIPTION
**Pull request by gklijs**
…ns, as well as subscriptions to be executed using web sockets

TODO:
- ~~Wait till change in micronaut-core is merged and set version to non-snapshot~~
- ~~Add subscriptions/ws to GraphiQL when enabled~~
- ~~Add support keep alive messages~~
- ~~Add tests~~
- ~~Add examples~~
- ~~Update documentation~~

### CODE REVIEW

**Comment by gklijs** [comment]
The pr for micronaut-core is merged.
I hope they create a milestone release soon. Then I can update to the milestone version in this pr, and the ci should succeed.

**Comment by marceloverdijk** [comment]
Let's target this for Micronaut-GraphQL `1.3.0`. As soon as Micronaut Core does a new milestone release we can make a `1.3.0.M1` milestone release as well including the subscriptions support.
Thanks for the work you done @gklijs  👍

**Comment by marceloverdijk** [comment]
👍 maybe it's an idea to setup an additional demo in https://github.com/micronaut-projects/micronaut-graphql/tree/master/examples showcasing the subscriptions support?

**Comment by gklijs** [comment]
That makes sense, was already something that crossed my mind. Will pick it up in a few days.

**Comment by gklijs** [comment]
Put them in a separate package. Unfortunately current master is failing, and I can't see the logs in Travis. @marceloverdijk could you please fix master?

**Comment by marceloverdijk** [comment]
@graemerocher the `micronaut-graphql` snapshots seem to fail publishing:

> Failed to publish publication 'maven' to repository 'maven'
   > Could not write to resource 'https://repo.micronaut.io/artifactory/libs-releases-local/io/micronaut/graphql/micronaut-graphql/1.3.0.BUILD-SNAPSHOP/micronaut-graphql-1.3.0.BUILD-SNAPSHOP.jar'.
      > repo.micronaut.io: Name or service not known

I noticed the other projects updated to use Github actions, could this be the issue?
Are there any steps to follow to upgrade `micronaut-graphql` to Github actions as well?

**Comment by jameskleeh** [comment]
@marceloverdijk repo.micronaut.io does not exist. This repo needs updated to our newest publishing standards

**Comment by marceloverdijk** [comment]
@jameskleeh Yes that is what I thought. Best to take one of the other repo's as example? I can imagine they don't use all the same so any recommended repo to follow?

**Comment by jameskleeh** [comment]
You can reference https://github.com/micronaut-projects/micronaut-ratelimiter

**Comment by marceloverdijk** [comment]
@jameskleeh I've updated the build but I'm getting now a `Could not PUT 'https://oss.jfrog.org/oss-snapshot-local/io/micronaut/graphql/micronaut-graphql/1.3.0.BUILD-SNAPSHOT/maven-metadata.xml'.`
Does Micronaut GraphQL need to be configured in jfrog maybe?

**Comment by jameskleeh** [comment]
I don't think so. "Received status code 401 from server". The credentials are just missing. I'll add them

**Comment by jameskleeh** [comment]
@marceloverdijk Build passed

**Comment by marceloverdijk** [comment]
@gklijs I upgraded `master` to the new publishing standards. This might affect your PR; probably good to rebase it with `master`. When you are done I think we can make a Micronaut-GraphQL `1.3.0.RC1` release 💪 and a final release next week.

**Comment by gklijs** [comment]
Had to fix a bit, it's rebased and ready now.

**Comment by marceloverdijk** [comment]
Thx a lot @gklijs !

@jameskleeh releasing of GA's and RC's is that still done automatically when creating the appropriate tags with the new publishing standards?

**Comment by graemerocher** [comment]
Nice work. Thanks for the PR!

**Comment by graemerocher** [comment]
@marceloverdijk I have updated the README with release instructions https://github.com/micronaut-projects/micronaut-graphql/commit/78eacdc27730e5ecea8b50ea875e13a41a24d619

**Comment by marceloverdijk** [comment]
@gklijs `1.3.0.RC1` is now synced to Maven Central.

**Pull request merged**
